name: active_learning
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.9
  - gpytorch=1.4.1
  - pytorch=1.8.1
  - cudatoolkit=10.2
  - torchvision
  - ray-tune
  - numpy
  - tensorboard
  - scikit-learn
  - matplotlib
  - pillow
  - ignite
  - pip
  - pip:
    - toma
    - torchtyping
    - tqdm
    - dragonfly-opt
