name: active_learning
channels:
  - pytorch-nightly
  - conda-forge
  - anaconda
dependencies:
  - python==3.8
  - gpytorch==1.4.0
  - pytorch
  - cudatoolkit=10.2
  - numpy
  - torchvision
  - marshmallow-dataclass
  - scikit-learn
  - ignite
  - requests
  - tensorboardx
  - ray-tune
  - ray-dashboard
  - pip
  - pip:
    - toma
    - batchbald_redux==2.0.2