name: active_learning
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python==3.8
  - gpytorch
  - pytorch
  - cudatoolkit=10.2
  - numpy
  - torchvision
  - marshmallow-dataclass
  - pip
  - pip:
    - toma
    - batchbald_redux